# Generated by Django 5.0.7 on 2024-07-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_puntos_num_puntos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puntos',
        ),
    ]
